create table if not exists public.community_reports (
  id bigint generated by default as identity primary key,
  latitude double precision not null,
  longitude double precision not null,
  issue_type text not null,
  description text not null,
  image_url text,
  reported_by text not null,
  created_at timestamp with time zone default now()
);
