import dotenv from "dotenv";
import { Resend } from "resend";

dotenv.config();

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendEmergencyEmail({
  to,
  userName,
  userPhone,
  contactName,
  mapsUrl,
  latitude,
  longitude,
}) {
  try {
    // ─────────────────────────────────────────────
    // Validate Environment Variables
    // ─────────────────────────────────────────────
    if (!process.env.RESEND_API_KEY) {
      throw new Error("RESEND_API_KEY is missing in .env");
    }

    if (!process.env.FROM_EMAIL) {
      throw new Error("FROM_EMAIL is missing in .env");
    }

    if (!to) {
      throw new Error("Emergency contact email is missing.");
    }

    console.log("\n========== RESEND ==========");
    console.log("To         :", to);
    console.log("From       :", process.env.FROM_EMAIL);
    console.log("User       :", userName);
    console.log("Phone      :", userPhone);
    console.log("Maps URL   :", mapsUrl);
    console.log("============================\n");

    const response = await resend.emails.send({
      from: process.env.FROM_EMAIL,
      to: [to],
      subject: "🚨 Safe Streets Emergency Alert",

      html: `
      <div style="font-family:Arial,sans-serif;padding:20px">

        <h2 style="color:#d32f2f;">
          🚨 Safe Streets Emergency Alert
        </h2>

        <p>Hello <strong>${contactName}</strong>,</p>

        <p>
          <strong>${userName}</strong> has triggered an SOS alert.
        </p>

        <p>
          <strong>Phone Number:</strong>
          ${userPhone}
        </p>

        <p>
          <strong>Current Location</strong>
        </p>

        <p>
          <a href="${mapsUrl}">
            Open Live Location in Google Maps
          </a>
        </p>

        <p>
          Latitude : ${latitude}<br>
          Longitude : ${longitude}
        </p>

        <hr>

        <p>
          This email was automatically generated by
          <strong>Safe Streets</strong>.
        </p>

      </div>
      `,
    });

    console.log("✅ Email sent successfully!");
    console.log(response);

    return {
      success: true,
      data: response,
    };
  } catch (err) {
    console.error("\n❌ RESEND ERROR");
    console.error(err);

    if (err.message) {
      console.error("Message:", err.message);
    }

    if (err.statusCode) {
      console.error("Status:", err.statusCode);
    }

    if (err.response) {
      console.error(err.response);
    }

    return {
      success: false,
      error: err.message || "Unknown email error",
    };
  }
}