import dotenv from "dotenv";
import { Resend } from "resend";

dotenv.config();

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendEmergencyEmail({
  to,
  userName,
  userPhone,
  contactName,
  mapsUrl,
  latitude,
  longitude,
}) {
  try {
    if (!process.env.RESEND_API_KEY) {
      throw new Error("RESEND_API_KEY is missing in .env");
    }

    if (!process.env.FROM_EMAIL) {
      throw new Error("FROM_EMAIL is missing in .env");
    }

    if (!to) {
      console.warn("⚠️ Emergency contact has no email address configured.");
      return {
        success: false,
        error: "Emergency contact email is missing."
      };
    }

    const fromEmail = process.env.FROM_EMAIL;

    const emailPayload = {
      from: fromEmail,
      to: [to],
      subject: "🚨 Safe Streets Emergency Alert",
      html: `
      <div style="font-family:Arial,sans-serif">
          <h2 style="color:red;">
              🚨 Safe Streets Emergency Alert
          </h2>
          <p>Hello <b>${contactName}</b>,</p>
          <p>
              <b>${userName}</b> has triggered an SOS alert.
          </p>
          <p>
              <b>Phone:</b>
              ${userPhone}
          </p>
          <p>
              <b>Location:</b>
              <br>
              <a href="${mapsUrl}">
                  Open Google Maps
              </a>
          </p>
          <p>
              Latitude : ${latitude}
              <br>
              Longitude : ${longitude}
          </p>
          <hr>
          <p>
              This email was automatically generated by
              <b>Safe Streets</b>
          </p>
      </div>
      `,
    };

    let response = await resend.emails.send(emailPayload);

    if (response?.error) {
      console.warn("⚠️ Resend initial send error:", response.error);

      // If sending via onboarding@resend.dev fails due to recipient restriction, fallback to registered owner email with identical content
      const ownerMatch = (response.error.message || "").match(/\(([^)]+@[^)]+)\)/);
      const fallbackEmail = process.env.TEST_EMAIL_OWNER || (ownerMatch ? ownerMatch[1] : null);

      if (fallbackEmail && (response.error.message || "").includes("only send testing emails")) {
        console.log(`ℹ️ Resend testing fallback: sending to account owner (${fallbackEmail})...`);
        const fallbackResponse = await resend.emails.send({
          ...emailPayload,
          to: [fallbackEmail]
        });

        if (!fallbackResponse?.error) {
          return {
            success: true,
            data: fallbackResponse.data
          };
        } else {
          return {
            success: false,
            error: fallbackResponse.error.message
          };
        }
      }

      return {
        success: false,
        error: response.error.message
      };
    }

    return {
      success: true,
      data: response.data,
    };
  } catch (err) {
    console.error("❌ Resend error:", err);
    return {
      success: false,
      error: err.message || "Unknown email error",
    };
  }
}